create table driver (driver_id integer generated by default as identity (start with 1), driver_dn varchar(255), driver_guid varchar(255), driver_type varchar(255), driver_version varchar(255), driver_image_url varchar(255), primary key (driver_id))
create table driverLabel (driverlabel_id integer generated by default as identity (start with 1), language_id integer not null, value varchar(255) not null, token varchar(255) not null, driver_id integer not null, primary key (driverlabel_id))
create table entitlement (entitlement_id integer generated by default as identity (start with 1), entitlement_cn varchar(255), query varchar(255), refresh_frequency integer, last_refresh integer, driver_id integer not null, primary key (entitlement_id))
create table entitlementLabel (entitlementlabel_id integer generated by default as identity (start with 1), language_id integer not null, value varchar(255) not null, token varchar(255) not null, entitlement_id integer not null, primary key (entitlementlabel_id))
create table entitlementconfig (entitlementconfig_id integer generated by default as identity (start with 1), entitlementconfig_dn varchar(255), min_version varchar(255), accepted_type varchar(255), driver_id integer not null, primary key (entitlementconfig_id))
create table host (host_id integer not null  , host_address varchar(255) not null, host_port integer, proxy_admin_id varchar(255), proxy_admin_pwd varchar(30), uad_dn varchar(255), host_ssl bit, user_root_dn varchar(255), nam_url varchar(255), rbpm_rest_url varchar(255), driver_discovery_dn varchar(255), display_name varchar(255),  active_status boolean , primary key ( display_name ))
create table language (language_id integer generated by default as identity (start with 1), langcode varchar(10) not null, primary key (language_id))
create table logicalsystem (logicalsystem_id integer generated by default as identity (start with 1), logicalsystem_name varchar(255), driver_id integer not null, primary key (logicalsystem_id))
create table logicalsystemLabel (logicalsystemlabel_id integer generated by default as identity (start with 1), language_id integer not null, value varchar(255) not null, token varchar(255) not null, logicalsystem_id integer not null, primary key (logicalsystemlabel_id))
create table logicalsystemlanguage (language_id integer generated by default as identity (start with 1), langcode varchar(10) not null, logicalsystem_id integer not null, loaded_entitlements varchar(512), primary key (language_id))
create table queryResultLabel (queryresultlabel_id integer generated by default as identity (start with 1), language_id integer not null, value varchar(255) not null, token varchar(255) not null, queryresult_id integer not null, primary key (queryresultlabel_id))
create table queryresult (queryresult_id integer generated by default as identity (start with 1), value varchar(255), subtype varchar(255), param_value varchar(255), default_description varchar(255), default_display_name varchar(255), entitlement_id integer not null, logicalsystem_id integer not null, primary key (queryresult_id))
create table mappingColumnConfig (columnconfig_id integer not null, show_auth_name bit, show_auth_type bit, show_auth_desc bit, primary key (columnconfig_id))
create table resourceCreationConfig (resourceconfig_id integer generated by default as identity (start with 1), host varchar(255) not null, driver varchar(255) not null, logical_system varchar(255) not null, resource_category varchar(255), use_system_name_prefix bit, use_driver_name_prefix bit, prefix_delimiter varchar(255), primary key (resourceconfig_id))
alter table driverLabel add constraint FK_driverlabel_driver foreign key (driver_id) references driver
alter table driverLabel add constraint FK_driverlabel_language foreign key (language_id) references language
alter table entitlement add constraint FK_entitlement_driver foreign key (driver_id) references driver
alter table entitlementLabel add constraint FK_entitlementlabel_entitlement foreign key (entitlement_id) references entitlement
alter table entitlementLabel add constraint FK_entitlementlabel_language foreign key (language_id) references language
alter table entitlementconfig add constraint FK_entitlementconfig_driver foreign key (driver_id) references driver
alter table logicalsystem add constraint FK_logicalsystem_driver foreign key (driver_id) references driver
alter table logicalsystemLabel add constraint FK_logicalsystemlabel_logicalsystem foreign key (logicalsystem_id) references logicalsystem
alter table logicalsystemLabel add constraint FK_logicalsystemlabel_language foreign key (language_id) references language
alter table logicalsystemlanguage add constraint FK_logicalsystemlanguage_logicalsystem foreign key (logicalsystem_id) references logicalsystem
alter table queryResultLabel add constraint FK_queryresultlabel_queryresult foreign key (queryresult_id) references queryresult
alter table queryResultLabel add constraint FK_queryresultlabel_logicalsystemlanguage foreign key (language_id) references logicalsystemlanguage
alter table queryresult add constraint FK_queryresult_logicalsystem foreign key (logicalsystem_id) references logicalsystem
alter table queryresult add constraint FK_queryresult_entitlement foreign key (entitlement_id) references entitlement
alter table resourceCreationConfig  add constraint FK_resourcecreationconfig_host foreign key (host) references host(display_name) on delete cascade
insert into language values(1,'en')